# Generated by Django 5.0.3 on 2024-04-25 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
        ),
    ]
