# Generated by Django 5.0.3 on 2024-04-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
