# Generated by Django 5.0.3 on 2024-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='default_image_url', max_length=300),
        ),
    ]
